#重定向检测防护过滤器配置,使用文档:https://yuque.antfin-inc.com/product_sec/secueirt-core-doc/xld82q
alipay.security.core.redirect.redirectCheckFilter=true
alipay.security.core.redirect.redirectWhiteHostList=antgroup-inc.cn
#alipay.security.core.redirect.whiteHostList
#alipay.security.core.redirect.schemeList
#alipay.security.core.redirect.urlWhiteList
alipay.security.core.redirect.exceptionMsg=Invalid Url Info
